// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArrayFeatureExtractor.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreML.Specification {

  /// <summary>Holder for reflection information generated from ArrayFeatureExtractor.proto</summary>
  public static partial class ArrayFeatureExtractorReflection {

    #region Descriptor
    /// <summary>File descriptor for ArrayFeatureExtractor.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArrayFeatureExtractorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtBcnJheUZlYXR1cmVFeHRyYWN0b3IucHJvdG8SFENvcmVNTC5TcGVjaWZp",
            "Y2F0aW9uIi0KFUFycmF5RmVhdHVyZUV4dHJhY3RvchIUCgxleHRyYWN0SW5k",
            "ZXgYASADKARCAkgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreML.Specification.ArrayFeatureExtractor), global::CoreML.Specification.ArrayFeatureExtractor.Parser, new[]{ "ExtractIndex" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// An array feature extractor.
  ///
  /// Given an index, extracts the value at that index from its array input.
  /// Indexes are zero-based.
  /// </summary>
  public sealed partial class ArrayFeatureExtractor : pb::IMessage<ArrayFeatureExtractor> {
    private static readonly pb::MessageParser<ArrayFeatureExtractor> _parser = new pb::MessageParser<ArrayFeatureExtractor>(() => new ArrayFeatureExtractor());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ArrayFeatureExtractor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreML.Specification.ArrayFeatureExtractorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArrayFeatureExtractor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArrayFeatureExtractor(ArrayFeatureExtractor other) : this() {
      extractIndex_ = other.extractIndex_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArrayFeatureExtractor Clone() {
      return new ArrayFeatureExtractor(this);
    }

    /// <summary>Field number for the "extractIndex" field.</summary>
    public const int ExtractIndexFieldNumber = 1;
    private static readonly pb::FieldCodec<ulong> _repeated_extractIndex_codec
        = pb::FieldCodec.ForUInt64(10);
    private readonly pbc::RepeatedField<ulong> extractIndex_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> ExtractIndex {
      get { return extractIndex_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ArrayFeatureExtractor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ArrayFeatureExtractor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!extractIndex_.Equals(other.extractIndex_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= extractIndex_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      extractIndex_.WriteTo(output, _repeated_extractIndex_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += extractIndex_.CalculateSize(_repeated_extractIndex_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ArrayFeatureExtractor other) {
      if (other == null) {
        return;
      }
      extractIndex_.Add(other.extractIndex_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            extractIndex_.AddEntriesFrom(input, _repeated_extractIndex_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
